server:
  port: 8091
spring:
  application:
    name: yingxue-administrators
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker2:3306/yingxue?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1111

  redis:
    host: 192.168.10.12
    port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.12:8848
        username: nacos
        password: nacos
        namespace: 064a5843-d39b-4188-a7ba-53bc9e573d51

#mybatis-plus
mybatis-plus:
  type-aliases-package: com.agg.yingxue.administrators.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
