server:
  port: 8090
spring:
  application:
    name: yingxue-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.12:8848
        username: nacos
        password: nacos
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes: #后续增加路由配置

