server:
  port: 8090
spring:
  application:
    name: yingxue-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.12:8848
        username: nacos
        password: nacos
        namespace: 064a5843-d39b-4188-a7ba-53bc9e573d51
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes: #后续增加路由配置
        - id: Yuser
          uri: lb://yingxue-users
          predicates:
            - Path=/user/**

        - id: Ycategory
          uri: lb://yingxue-category
          predicates:
            - Path=/category/**

        - id: Yvideo
          uri: lb://yingxue-videos
          predicates:
            - Path=/video/**

